### PR TITLE
Shortcuts for keywords

### PR DESCRIPTION
**Pull request by maximkoretskiy**
Your plugin is great! 
For more convenient usage some users would like to use their own naming.

For example it would be nice to name descendents as elements if U use bem. Or use 1 letter shortening to create more compact code.

```css
@b nav { /* b is for block */
    @e item { /* e is for element */
        display: inline-block;
    }
    @m placement_header {
        background-color: red;
    }
}
```

### CODE REVIEW

**Comment by ai** [comment]
I like it! With this short and clear at-rules you will have much more users from BEM.

Also I will be happy if you accept this PR on this week, so I can include your plugin to my talk (current at-rules is too long and unusual).

**Comment by ai** [comment]
@ileri ping?

**Comment by ai** [comment]
@ileri any comments? :)

**Comment by maximkoretskiy** [comment]
:+1:

**Pull request merged**
